# Generated by Django 4.2.27 on 2026-01-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_part_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_part_name',
            field=models.CharField(blank=True, help_text='For parts not yet in inventory', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.carpart'),
        ),
    ]
