# Generated by Django 4.2.27 on 2026-03-14 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_company_alter_carpart_location_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_external',
            field=models.TextField(blank=True, help_text='Shipping address for external partners', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_orders', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('SALE', 'Sale to Customer'), ('TRANSFER', 'Warehouse Transfer'), ('PURCHASE', 'Purchase/Restock'), ('ADJUSTMENT', 'Manual Adjustment/Loss')], default='SALE', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_orders', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_part_name',
            field=models.CharField(blank=True, help_text='For items not in database', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='inventory.order')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.carpart')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
    ]
