# Generated by Django 4.2.27 on 2026-03-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_order_destination_external_order_from_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_parts', to='inventory.company'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='carpart',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='unique_sku_per_company'),
        ),
    ]
