# Generated by Django 4.2.27 on 2026-03-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_carpart_company_alter_carpart_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpart',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.warehouse'),
        ),
    ]
