# Generated by Django 4.2.27 on 2026-03-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_carpart_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='inventory.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('location', models.CharField(help_text='Shelf/Bin (e.g., A1-B2)', max_length=100)),
                ('company_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.companyproduct')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.warehouse')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='custom_part_description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destination_external',
        ),
        migrations.RemoveField(
            model_name='order',
            name='part',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='part',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('SALE', 'Sale to Customer'), ('TRANSFER', 'Internal Warehouse Transfer'), ('PURCHASE', 'Purchase/Restock'), ('ADJUSTMENT', 'Manual Adjustment/Loss')], default='SALE', max_length=20),
        ),
        migrations.DeleteModel(
            name='CarPart',
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_listings', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.companyproduct'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='warehouse_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehousestock'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'company_product'), name='unique_stock_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='companyproduct',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='unique_sku_per_company'),
        ),
        migrations.AddConstraint(
            model_name='companyproduct',
            constraint=models.UniqueConstraint(fields=('company', 'product'), name='unique_product_per_company'),
        ),
    ]
