# Generated by Django 4.2.27 on 2026-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_companyproduct_product_warehousestock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproduct',
            name='sharing_mode',
            field=models.CharField(choices=[('INTERNAL', 'Internal Only (Private)'), ('WAREHOUSE_LIMIT', 'Warehouse Buffer (Share surplus)'), ('MARKET_FIXED', 'Fixed Quantity (Share specific amount)'), ('GLOBAL', 'All Shared (Public)')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='sharing_value',
            field=models.IntegerField(default=0, help_text='Limit or Fixed amount depending on mode'),
        ),
    ]
