# Generated by Django 4.2.27 on 2026-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_companyproduct_sharing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_external',
            field=models.CharField(blank=True, help_text='Name of external source/destination if not an internal warehouse transfer.', max_length=255, null=True),
        ),
    ]
