# Generated by Django 4.2.27 on 2026-03-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_order_destination_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
