# Generated by Django 4.2.27 on 2026-03-17 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vin',
            field=models.CharField(help_text='17-character unique Vehicle Identification Number', max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.RegexValidator(message='VIN must be 17 alphanumeric characters and exclude I, O, and Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
    ]
