# Generated by Django 4.2.27 on 2026-03-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_company_ai_strategy_company_prediction_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ai_strategy',
        ),
        migrations.AddField(
            model_name='company',
            name='service_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
