# Generated by Django 4.2.27 on 2026-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_company_ai_strategy_company_service_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='service_level',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
    ]
