# Generated by Django 4.2.27 on 2026-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_company_service_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_epochs',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_update_frequency',
            field=models.IntegerField(default=24, help_text='Update frequency in hours'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('SALE', 'Sale to Customer'), ('TRANSFER', 'Internal Warehouse Transfer'), ('PURCHASE', 'Purchase/Restock'), ('ADJUSTMENT', 'Manual Adjustment/Loss'), ('CONSUME', 'Consumed for Repair')], default='SALE', max_length=20),
        ),
    ]
