# Generated by Django 4.2.29 on 2026-03-19 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_company_ai_epochs_company_ai_update_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_historical',
            field=models.BooleanField(default=False, help_text='Used for AI training only, skips stock updates.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
