# Generated by Django 4.2.27 on 2026-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_order_is_historical_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='ai_stock_floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='last_ai_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyproduct',
            name='sharing_mode',
            field=models.CharField(choices=[('INTERNAL', 'Internal Only (Private)'), ('WAREHOUSE_LIMIT', 'Warehouse Buffer (Share surplus)'), ('AI_BUFFER', 'AI Predicted Buffer (Auto-share surplus)'), ('MARKET_FIXED', 'Fixed Quantity (Share specific amount)'), ('GLOBAL', 'All Shared (Public)')], default='INTERNAL', max_length=20),
        ),
    ]
