# Generated by Django 4.2.29 on 2026-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_warehousestock_ai_stock_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overwrites company price for this specific warehouse.', max_digits=10, null=True),
        ),
    ]
