# Generated by Django 4.2.29 on 2026-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_warehouse_latitude_warehouse_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='longitude',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country_code',
            field=models.CharField(choices=[('LV', 'Latvia (LV)'), ('LT', 'Lithuania (LT)'), ('EE', 'Estonia (EE)'), ('DE', 'Germany (DE)'), ('PL', 'Poland (PL)'), ('FI', 'Finland (FI)'), ('SE', 'Sweden (SE)'), ('GB', 'Great Britain (GB)'), ('US', 'United States (US)'), ('FR', 'France (FR)'), ('IT', 'Italy (IT)'), ('ES', 'Spain (ES)'), ('NL', 'Netherlands (NL)'), ('OT', 'Other (OT)')], default='LV', help_text='Two-letter ISO country code for the warehouse location', max_length=2),
        ),
    ]
