import { defineStore } from 'pinia';

export const useConfigStore = defineStore('config', {
  state: () => ({
    language: localStorage.getItem('app-lang') || 'en',
    theme: localStorage.getItem('app-theme') || 'dark',
    translations: {
      en: {
        common: {
          loading: 'Loading...',
          error: 'Error',
          save: 'Save',
          cancel: 'Cancel',
          delete: 'Delete',
          search: 'Search',
          actions: 'Actions',
          noData: 'No data available.'
        },
        nav: {
          inventory: 'Inventory',
          orders: 'Orders',
          market: 'Market',
          exchange: 'Exchange',
          forecast: 'AI Forecast',
          tuning: 'AI Tuning',
          settings: 'Settings',
          addPart: 'Add Part',
          logout: 'Logout',
          signIn: 'Sign In',
          register: 'Register'
        },
        auth: {
          loginTitle: 'Welcome Back',
          loginSubtitle: 'Sign in to AI Warehouse',
          registerTitle: 'Create Account',
          registerSubtitle: 'Join the team',
          username: 'Username',
          password: 'Password',
          email: 'Email (Optional)',
          usernamePlaceholder: 'Enter username',
          passwordPlaceholder: 'Enter password',
          emailPlaceholder: 'your@email.com',
          regUsernamePlaceholder: 'Choose a username',
          regPasswordPlaceholder: 'Choose a secure password',
          signIn: 'Sign In',
          signingIn: 'Signing In...',
          register: 'Register',
          creatingAccount: 'Creating Account...',
          noAccount: "Don't have an account?",
          alreadyAccount: 'Already have an account?',
          invalidAuth: 'Invalid username or password.',
          regFailed: 'Registration failed. Please try again.',
          companyName: 'Company Name',
          initialWarehouse: 'Initial Warehouse'
        },
        roles: {
          admin: 'Admin',
          ceo: 'CEO',
          manager: 'Warehouse Manager',
          mechanic: 'Mechanic',
          label: 'Role'
        },
        dashboard: {
          title: 'Company Administration',
          subtitle: 'Manage employee access, roles, and accounts',
          employees: 'Employee Management',
          privileges: 'Manage employee roles and account access',
          staffOverview: 'Staff Overview',
          totalEmployees: 'Total Employees:',
          helpText: 'You can promote/demote staff or remove access entirely. Note: You cannot delete your own account.',
          loadingDirectory: 'Loading directory...',
          errorLoad: 'Failed to load employee directory.',
          revokeAccess: 'Revoke Access',
          noEmployees: 'No other employees found in your company.',
          confirmDelete: "Are you sure you want to delete {username}'s account? This action is permanent.",
          failUpdateRole: 'Failed to update user role.',
          failDelete: 'Failed to delete user account.'
        },
        inventory: {
          title: "Warehouse Inventory",
          addNew: "Add New Part",
          requestNew: "Request New Part",
          empty: "No parts in inventory. Start by adding some.",
          errorLoad: "Failed to load inventory.",
          editPart: "Edit Part",
          partName: "Part Name",
          vin: "VIN (Vehicle Identification Number)",
          vinHelp: "Standard 17-char unique identifier for part identity tracking.",
          sku: "SKU",
          location: "Location",
          quantity: "Quantity",
          price: "Price ($)",
          sharing: "Global Market Sharing",
          description: "Description",
          savePart: "Save Part",
          saving: "Saving...",
          failLoadPart: "Failed to load part data.",
          failSavePart: "Failed to {action} part. Please check your inputs.",
          placeholders: {
            name: "e.g. Brake Pads",
            vin: "17 alphanumeric characters",
            sku: "BP-1234",
            location: "A1-R2",
            description: "Additional details..."
          },
          order: "Order",
          use: "Use",
          transfer: "Transfer",
          qtyShort: "Qty",
          locShort: "Loc",
          priceShort: "Price",
          confirmDelete: "Are you sure you want to delete {name} from this warehouse?",
          aiThreshold: "AI Threshold"
        },
        market: {
          title: "Global Market",
          subtitle: "Parts shared by partner companies",
          searchPlaceholder: "Search by name, SKU or company...",
          sortBy: "Sort by:",
          sortDefault: "Sort by",
          productName: "Product Name",
          priceLowHigh: "Price: Low to High",
          priceHighLow: "Price: High to Low",
          quantity: "Largest Quantity",
          scanning: "Scanning the global market...",
          errorLoad: "Failed to load market data.",
          noItems: "No items found matching your criteria."
        },
        orders: {
          title: "Company Orders",
          subtitle: "Track and manage inventory movements",
          completeAll: "Complete All Pending",
          loading: "Loading the paper trail...",
          errorLoad: "Failed to load orders.",
          noOrders: "No orders found for your company.",
          bulkConfirm: "⚠️ This will immediately COMPLETE all PENDING or APPROVED orders for the company. This will update stock levels for all items. Proceed?",
          rejectConfirm: "Are you sure you want to reject this order?",
          deleteConfirm: "Are you sure you want to delete this pending order?",
          approve: "Approve",
          reject: "Reject",
          complete: "Mark Completed",
          cancel: "Cancel/Delete",
          quantity: "Quantity",
          requestedBy: "Requested By",
          from: "From",
          to: "To",
          date: "Date",
          units: "units",
          placeOrder: "Place Order",
          requestPart: "Request Part",
          orderTitle: "Order {name} ({vin})",
          submitting: "Submitting...",
          buyFrom: "Buy from {company}",
          totalPrice: "Total Price",
          confirmPurchase: "Confirm Purchase",
          consumeTitle: "Use {name} on Car",
          vinPlaceholder: "Enter 17-char VIN",
          confirmConsume: "Confirm Usage",
          transferTitle: "Transfer {name}",
          targetWarehouse: "Target Warehouse",
          selectWarehouse: "Select Warehouse",
          confirmTransfer: "Confirm Transfer",
          failOrder: "Failed to place order. Please try again.",
          failConsume: "Failed to record usage. Please check stock.",
          failTransfer: "Failed to initiate transfer.",
          sellerWarehouse: "Seller Warehouse (Order From)",
          destinationWarehouse: "Destination Warehouse (Send To)",
          checkingAvailability: "Checking availability...",
          noStock: "No stock available in any warehouse.",
          restrictedWarehouse: "Mechanics are restricted to their assigned warehouse.",
          yourWarehouse: "Your Assigned Warehouse",
          selectWarehouses: "Please select both source and destination warehouses.",
          processing: "Processing...",
          takingFrom: "Taking From",
          carVin: "Car VIN or License Plate",
          insufficientStock: "Insufficient stock. Only {qty} available.",
          recordUsage: "Record Usage",
          recording: "Recording...",
          movingFrom: "Moving From",
          moveTo: "Move To (Destination)",
          startTransfer: "Start Transfer",
          noOtherWarehouses: "No other warehouses found",
          selectDestination: "Please select a destination warehouse.",
          insufficientStockLabel: "Quantity Used (Available: {qty})"
        },
        ai: {
          title: "AI Inventory Forecasting",
          subtitle: "Smart prediction of stock floors based on historical demand",
          parameters: "Prediction Parameters",
          serviceLevel: "Customer Service Level",
          lean: "90% (Lean)",
          aggressive: "99.5% (Aggressive)",
          serviceLevelHelp: "Target probability of avoiding stock-outs. Higher levels increase safety stock but raise carrying costs.",
          horizon: "Prediction Horizon (Days)",
          horizonHelp: "How long do you want the stock to last before replenishment?",
          updateButton: "Update Prediction Model",
          savingRules: "Saving Rules...",
          stockFloors: "Calculated Stock Floors",
          refresh: "Refresh Data",
          runningForecast: "Running AI Forecast...",
          onHand: "On Hand",
          recommendedFloor: "AI Recommended Floor",
          forecastLogic: "Forecast Logic",
          noItems: "No stock items found for forecasting.",
          forecastTitle: "AI Inventory Forecasting",
          tuningTitle: "AI System Administration",
          initiateTraining: "Initiate Global Training",
          admin: {
            title: "Global AI Control Center",
            subtitle: "Multi-tenant Model Lifecycle Management",
            trainAll: "Train All Companies",
            processingBulk: "Processing Bulk Training...",
            fetchingTiers: "Fetching Company AI Tiers...",
            updatedSettings: "Updated settings for {company}.",
            trainSuccess: "Training initiated for {company}.",
            trainFail: "Training failed for {company}.",
            globalFail: "Global training cycle failed to initiate.",
            retrain: "Retrain AI",
            saveRules: "Save Rules",
            epochs: "Training Epochs",
            frequency: "Inference Frequency",
            targetLevel: "Target Level",
            cycles: "Cycles",
            hours: "Hours",
            noCompanies: "No companies registered in the system.",
            forbidden: "403 - Restricted Access",
            restricted: "System Administrator privileges required for Multi-tenant AI control."
          }
        },
        exchange: {
          title: "Data Exchange",
          subtitle: "Streamline your data flow between warehouses and external systems",
          inventoryParts: "Inventory (Parts)",
          historyOrders: "History (Orders)",
          export: "Export",
          import: "Import",
          exportDescParts: "Download your current warehouse inventory listing, including current quantities and shelf locations.",
          exportDescOrders: "Download your entire company order history as a CSV file compatible with Excel and Google Sheets.",
          importDescParts: "Batch upload new parts. Headers: name, vin, sku, quantity, price, location, description.",
          importDescOrders: "Bulk upload historical order data for AI Training. Headers: order_type, vin, quantity, from_warehouse, to_warehouse, status, destination_external, date.",
          preparingFile: "Preparing File...",
          downloadCsv: "Download CSV",
          selectCsv: "Select CSV File",
          importing: "Importing...",
          startBatch: "Start Batch Upload",
          importComplete: "Import Complete!",
          processed: "Processed",
          items: "items",
          warnings: "Warnings:",
          failExport: "Failed to export {type}.",
          failImport: "Import failed. Ensure CSV format is correct."
        },
        sharing: {
          internal: 'Internal Only (Private)',
          warehouseLimit: 'Warehouse Buffer (Share surplus)',
          marketFixed: 'Fixed Quantity (Share specific amount)',
          global: 'All Shared (Public)',
          bufferLimit: 'Warehouse Buffer Limit',
          qtyToShare: 'Quantity to Share',
          bufferHelp: 'Items above this number in each warehouse will be shared.',
          fixedHelp: 'Exactly this many items will be visible on the market.'
        }
      },
      lv: {
        common: {
          loading: 'Ielādē...',
          error: 'Kļūda',
          save: 'Saglabāt',
          cancel: 'Atcelt',
          delete: 'Dzēst',
          search: 'Meklēt',
          actions: 'Darbības',
          noData: 'Dati nav pieejami.'
        },
        nav: {
          inventory: 'Noliktava',
          orders: 'Pasūtījumi',
          market: 'Tirgus',
          exchange: 'Datu apmaiņa',
          forecast: 'AI Prognoze',
          tuning: 'AI Konfigurācija',
          settings: 'Iestatījumi',
          addPart: 'Pievienot detaļu',
          logout: 'Iziet',
          signIn: 'Pierakstīties',
          register: 'Reģistrēties'
        },
        auth: {
          loginTitle: 'Sveicināti atpakaļ',
          loginSubtitle: 'Pierakstieties AI Warehouse',
          registerTitle: 'Izveidot kontu',
          registerSubtitle: 'Pievienojieties komandai',
          username: 'Lietotājvārds',
          password: 'Parole',
          email: 'E-pasts (neobligāti)',
          usernamePlaceholder: 'Ievadiet lietotājvārdu',
          passwordPlaceholder: 'Ievadiet paroli',
          emailPlaceholder: 'jusu@epasts.lv',
          regUsernamePlaceholder: 'Izvēlieties lietotājvārdu',
          regPasswordPlaceholder: 'Izvēlieties drošu paroli',
          signIn: 'Pierakstīties',
          signingIn: 'Pierakstās...',
          register: 'Reģistrēties',
          creatingAccount: 'Veido kontu...',
          noAccount: 'Nav konta?',
          alreadyAccount: 'Jau ir konts?',
          invalidAuth: 'Nepareizs lietotājvārds vai parole.',
          regFailed: 'Reģistrācija neizdevās. Lūdzu mēģiniet vēlreiz.',
          companyName: 'Uzņēmuma nosaukums',
          initialWarehouse: 'Sākotnējā noliktava'
        },
        roles: {
          admin: 'Administrators',
          ceo: 'Izpilddirektors',
          manager: 'Noliktavas vadītājs',
          mechanic: 'Mehāniķis',
          label: 'Loma'
        },
        dashboard: {
          title: 'Uzņēmuma administrēšana',
          subtitle: 'Pārvaldīt darbinieku piekļuvi, lomas un kontus',
          employees: 'Darbinieku pārvaldība',
          privileges: 'Pārvaldīt darbinieku lomas un piekļuvi',
          staffOverview: 'Personāla pārskats',
          totalEmployees: 'Kopā darbinieki:',
          helpText: 'Jūs varat paaugstināt/pazemināt personālu vai pilnībā noņemt piekļuvi. Piezīme: Jūs nevarat dzēst savu kontu.',
          loadingDirectory: 'Ielādē direktoriju...',
          errorLoad: 'Neizdevās ielādēt darbinieku direktoriju.',
          revokeAccess: 'Atņemt piekļuvi',
          noEmployees: 'Jūsu uzņēmumā nav citu darbinieku.',
          confirmDelete: "Vai tiešām vēlaties dzēst {username} kontu? Šī darbība ir neatgriezeniska.",
          failUpdateRole: 'Neizdevās atjaunināt lietotāja lomu.',
          failDelete: 'Neizdevās dzēst lietotāja kontu.'
        },
        inventory: {
          title: "Noliktavas Inventārs",
          addNew: "Pievienot jaunu detaļu",
          requestNew: "Pieprasīt jaunu detaļu",
          empty: "Noliktavā nav detaļu. Sāciet ar dažu pievienošanu.",
          errorLoad: "Neizdevās ielādēt inventāru.",
          editPart: "Rediģēt detaļu",
          partName: "Detaļas nosaukums",
          vin: "VIN (Transportlīdzekļa identifikācijas numurs)",
          vinHelp: "Standarta 17 rakstzīmju unikālais identifikators detaļas identitātes izsekošanai.",
          sku: "SKU",
          location: "Atrašanās vieta",
          quantity: "Daudzums",
          price: "Cena ($)",
          sharing: "Globālā tirgus koplietošana",
          description: "Apraksts",
          savePart: "Saglabāt detaļu",
          saving: "Saglabā...",
          failLoadPart: "Neizdevās ielādēt detaļas datus.",
          failSavePart: "Neizdevās {action} detaļu. Lūdzu, pārbaudiet ievadi.",
          placeholders: {
            name: "piem. Bremžu kluči",
            vin: "17 burtu un ciparu rakstzīmes",
            sku: "BP-1234",
            location: "A1-R2",
            description: "Papildu informācija..."
          },
          order: "Pasūtīt",
          use: "Izlietot",
          transfer: "Pārvietot",
          qtyShort: "Skaits",
          locShort: "Vieta",
          priceShort: "Cena",
          confirmDelete: "Vai tiešām vēlaties dzēst {name} no šīs noliktavas?",
          aiThreshold: "AI slieksnis"
        },
        market: {
          title: "Globālais tirgus",
          subtitle: "Detaļas, kuras kopīgo partneruzņēmumi",
          searchPlaceholder: "Meklēt pēc nosaukuma, SKU vai uzņēmuma...",
          sortBy: "Kārtot pēc:",
          sortDefault: "Kārtot pēc",
          productName: "Produkta nosaukums",
          priceLowHigh: "Cena: No zemākās uz augstāko",
          priceHighLow: "Cena: No augstākās uz zemāko",
          quantity: "Lielākais daudzums",
          scanning: "Skenē globālo tirgu...",
          errorLoad: "Neizdevās ielādēt tirgus datus.",
          noItems: "Netika atrasta neviena prece, kas atbilstu jūsu kritērijiem."
        },
        orders: {
          title: "Uzņēmuma Pasūtījumi",
          subtitle: "Izsekojiet un pārvaldiet inventāra kustību",
          completeAll: "Pabeigt visus neapstiprinātos",
          loading: "Notiek ielāde...",
          errorLoad: "Neizdevās ielādēt pasūtījumus.",
          rejectConfirm: "Vai tiešām vēlaties noraidīt šo pasūtījumu?",
          deleteConfirm: "Vai tiešām vēlaties dzēst šo neapstiprināto pasūtījumu?",
          bulkConfirm: "⚠️ Tas nekavējoties PABEIGS visus NEAPSTIPRINĀTOS vai APSTIPRINĀTOS uzņēmuma pasūtījumus. Tas atjauninās krājumu līmeni visām precēm. Turpināt?",
          quantity: "Daudzums",
          units: "vien.",
          requestedBy: "Pieprasīja",
          from: "No",
          to: "Uz",
          date: "Datums",
          approve: "Apstiprināt",
          reject: "Noraidīt",
          complete: "Atzīmēt kā pabeigtu",
          cancel: "Atcelt/Dzēst",
          noOrders: "Jūsu uzņēmumam nav atrasts neviens pasūtījums.",
          placeOrder: "Veikt pasūtījumu",
          requestPart: "Pieprasīt detaļu",
          orderTitle: "Pasūtīt {name} ({vin})",
          submitting: "Iesniedz...",
          buyFrom: "Pirkt no {company}",
          totalPrice: "Kopējā cena",
          confirmPurchase: "Apstiprināt pirkumu",
          consumeTitle: "Izlietot {name} automašīnai",
          vinPlaceholder: "Ievadiet 17 zīmju VIN",
          confirmConsume: "Apstiprināt izlietojumu",
          transferTitle: "Pārvietot {name}",
          targetWarehouse: "Mērķa noliktava",
          selectWarehouse: "Izvēlieties noliktavu",
          confirmTransfer: "Apstiprināt pārvietošanu",
          failOrder: "Neizdevās veikt pasūtījumu. Lūdzu, mēģiniet vēlreiz.",
          failConsume: "Neizdevās reģistrēt izlietojumu. Pārbaudiet krājumus.",
          failTransfer: "Neizdevās uzsākt pārvietošanu.",
          sellerWarehouse: "Pārdevēja noliktava (Pasūtīt no)",
          destinationWarehouse: "Mērķa noliktava (Sūtīt uz)",
          checkingAvailability: "Pārbauda pieejamību...",
          noStock: "Nevienā noliktavā nav pieejamu krājumu.",
          restrictedWarehouse: "Mehāniķi ir ierobežoti ar viņiem piešķirto noliktavu.",
          yourWarehouse: "Jūsu piešķirtā noliktava",
          selectWarehouses: "Lūdzu, izvēlieties gan avota, gan mērā noliktavu.",
          processing: "Apstrādā...",
          takingFrom: "Ņemts no",
          carVin: "Auto VIN vai numurzīme",
          insufficientStock: "Nepietiekami krājumi. Pieejami tikai {qty}.",
          recordUsage: "Reģistrēt izlietojumu",
          recording: "Reģistrē...",
          movingFrom: "Pārvieto no",
          moveTo: "Pārvieto uz (Mērķis)",
          startTransfer: "Sākt pārvietošanu",
          noOtherWarehouses: "Nav citu noliktavu",
          selectDestination: "Lūdzu, izvēlieties mērķa noliktavu.",
          insufficientStockLabel: "Izlietotais daudzums (Pieejams: {qty})"
        },
        ai: {
          title: "AI Inventāra Prognozēšana",
          subtitle: "Vieda krājumu līmeņu prognozēšana, balstoties uz vēsturisko pieprasījumu",
          parameters: "Prognozēšanas parametri",
          serviceLevel: "Pakalpojuma Līmenis",
          lean: "90% (Ekonomisks)",
          aggressive: "99.5% (Agresīvs)",
          serviceLevelHelp: "Mērķa varbūtība izvairīties no krājumu izbeigšanās. Augstāks līmenis palielina drošības krājumus, bet ceļ uzturēšanas izmaksas.",
          horizon: "Prognozes periods (dienas)",
          horizonHelp: "Cik ilgi vēlaties, lai krājumi būtu pietiekami pirms papildināšanas?",
          updateButton: "Atjaunināt prognozēšanas modeli",
          savingRules: "Saglabā...",
          stockFloors: "Aprēķinātie krājumu sliekšņi",
          refresh: "Atjaunināt datus",
          runningForecast: "Veic AI prognozēšanu...",
          onHand: "Pieejams",
          recommendedFloor: "AI ieteicamais slieksnis",
          forecastLogic: "Prognozes loģika",
          noItems: "Nav atrasta neviena prece prognozēšanai.",
          forecastTitle: "AI Krājumu prognozēšana",
          tuningTitle: "AI Sistēmas administrēšana",
          initiateTraining: "Sākt globālo apmācību",
          admin: {
            title: "Globālais AI Vadības Centrs",
            subtitle: "Daudzlietotāju modeļa dzīves cikla pārvaldība",
            trainAll: "Apmācīt visus uzņēmumus",
            processingBulk: "Notiek masveida apmācība...",
            fetchingTiers: "Iegūst uzņēmumu AI datus...",
            updatedSettings: "Atjaunināti iestatījumi uzņēmumam {company}.",
            trainSuccess: "Apmācība uzsākta uzņēmumam {company}.",
            trainFail: "Apmācība neizdevās uzņēmumam {company}.",
            globalFail: "Globālās apmācības ciklu neizdevās uzsākt.",
            retrain: "Pārmācīt AI",
            saveRules: "Saglabāt noteikumus",
            epochs: "Apmācības cikli (Epochs)",
            frequency: "Secinājumu biežums",
            targetLevel: "Mērķa līmenis",
            cycles: "Cikli",
            hours: "Stundas",
            noCompanies: "Sistēmā nav reģistrētu uzņēmumu.",
            forbidden: "403 - Piekļuve liegta",
            restricted: "Sistēmas administratora privilēģijas ir nepieciešamas AI kontrolei."
          }
        },
        exchange: {
          title: "Datu apmaiņa",
          subtitle: "Efektivizējiet datu plūsmu starp noliktavām un ārējām sistēmām",
          inventoryParts: "Inventārs (Detaļas)",
          historyOrders: "Vēsture (Pasūtījumi)",
          export: "Eksportēt",
          import: "Importēt",
          exportDescParts: "Lejupielādējiet pašreizējo noliktavas inventāra sarakstu, ieskaitot daudzumus un plauktu atrašanās vietas.",
          exportDescOrders: "Lejupielādējiet visu uzņēmuma pasūtījumu vēsturi kā CSV failu, kas saderīgs ar Excel un Google Sheets.",
          importDescParts: "Pievienot detaļas lielos apjomos. Galvenes: name, vin, sku, quantity, price, location, description.",
          importDescOrders: "Augšupielādēt vēsturiskos pasūtījumu datus AI apmācībai. Galvenes: order_type, vin, quantity, from_warehouse, to_warehouse, status, destination_external, date.",
          preparingFile: "Sagatavo failu...",
          downloadCsv: "Lejupielādēt CSV",
          selectCsv: "Izvēlēties CSV failu",
          importing: "Importē...",
          startBatch: "Sākt lielapjoma augšupielādi",
          importComplete: "Imports pabeigts!",
          processed: "Apstrādāts",
          items: "vienības",
          warnings: "Brīdinājumi:",
          failExport: "Neizdevās eksportēt {type}.",
          failImport: "Imports neizdevās. Pārliecinieties, vai CSV formāts ir pareizs."
        },
        sharing: {
          internal: 'Tikai iekšēji (Privāts)',
          warehouseLimit: 'Noliktavas buferis (Kopīgot pārsniegumu)',
          marketFixed: 'Fiksēts daudzums (Kopīgot konkrētu apjomu)',
          global: 'Viss kopīgots (Publisks)',
          bufferLimit: 'Noliktavas bufera ierobežojums',
          qtyToShare: 'Daudzums kopīgošanai',
          bufferHelp: 'Preces virs šī skaita katrā noliktavā tiks kopīgotas.',
          fixedHelp: 'Tirgus vidē būs redzams tieši šāds preču skaits.'
        }
      }
    }
  }),
  getters: {
    t: (state) => (path) => {
      const keys = path.split('.');
      let result = state.translations[state.language];
      for (const key of keys) {
        if (result && result[key]) {
          result = result[key];
        } else {
          return path;
        }
      }
      return result;
    }
  },
  actions: {
    setLanguage(lang) {
      this.language = lang;
      localStorage.setItem('app-lang', lang);
    },
    toggleTheme() {
      this.theme = this.theme === 'dark' ? 'light' : 'dark';
      localStorage.setItem('app-theme', this.theme);
      this.applyTheme();
    },
    applyTheme() {
      document.documentElement.setAttribute('data-theme', this.theme);
    }
  }
});
